### ISSUE TITLE
AppImage: no breaks set. exiting

### ISSUE THREAD

**Issue by probonopd** [OneMoreGres/screendose#1]
```
firejail ./BeingTested.AppImage failed to open config file "settings.ini" No breaks added
no breaks set. exiting
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/1292

**Comment by OneMoreGres** [comment]
It must have config file to work properly (https://github.com/OneMoreGres/screendose#usage).
Sample config is \<repo>/share/settings.ini. I've copied it to releases.

**Comment by probonopd** [comment]
Could the application copy its config file there automatically upon first launch? So that the user doesn't have to do anyhting special to launch the application. (This would be needed for the application to pass our automated test.)

Thank you very much.

**Comment by OneMoreGres** [comment]
Added default config to resources

**Comment by OneMoreGres** [comment]
Guess it works..
